version: '3.8'

services:
  gateway:
    build:
      context: ./mom_gateway
    container_name: gateway
    command: ["172.31.23.47:50051", "172.31.21.77:50052", "172.31.27.228:50053"]
    ports:
      - "8080:8080"
    networks:
      - momnet

networks:
  momnet:
    driver: bridge
