// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: mom.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credenciales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credenciales) Reset() {
	*x = Credenciales{}
	mi := &file_mom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credenciales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credenciales) ProtoMessage() {}

func (x *Credenciales) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credenciales.ProtoReflect.Descriptor instead.
func (*Credenciales) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{0}
}

func (x *Credenciales) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credenciales) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenConExpiracion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiracion    string                 `protobuf:"bytes,3,opt,name=expiracion,proto3" json:"expiracion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenConExpiracion) Reset() {
	*x = TokenConExpiracion{}
	mi := &file_mom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenConExpiracion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenConExpiracion) ProtoMessage() {}

func (x *TokenConExpiracion) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenConExpiracion.ProtoReflect.Descriptor instead.
func (*TokenConExpiracion) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{1}
}

func (x *TokenConExpiracion) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenConExpiracion) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenConExpiracion) GetExpiracion() string {
	if x != nil {
		return x.Expiracion
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_mom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AccionConToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccionConToken) Reset() {
	*x = AccionConToken{}
	mi := &file_mom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccionConToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccionConToken) ProtoMessage() {}

func (x *AccionConToken) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccionConToken.ProtoReflect.Descriptor instead.
func (*AccionConToken) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{3}
}

func (x *AccionConToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccionConToken) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type MensajeConToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Contenido     string                 `protobuf:"bytes,3,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeConToken) Reset() {
	*x = MensajeConToken{}
	mi := &file_mom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeConToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeConToken) ProtoMessage() {}

func (x *MensajeConToken) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeConToken.ProtoReflect.Descriptor instead.
func (*MensajeConToken) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{4}
}

func (x *MensajeConToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MensajeConToken) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *MensajeConToken) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

type AutorizacionColaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Nombre          string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	UsuarioObjetivo string                 `protobuf:"bytes,3,opt,name=usuarioObjetivo,proto3" json:"usuarioObjetivo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AutorizacionColaRequest) Reset() {
	*x = AutorizacionColaRequest{}
	mi := &file_mom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutorizacionColaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutorizacionColaRequest) ProtoMessage() {}

func (x *AutorizacionColaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutorizacionColaRequest.ProtoReflect.Descriptor instead.
func (*AutorizacionColaRequest) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{5}
}

func (x *AutorizacionColaRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AutorizacionColaRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *AutorizacionColaRequest) GetUsuarioObjetivo() string {
	if x != nil {
		return x.UsuarioObjetivo
	}
	return ""
}

type MensajeTexto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contenido     string                 `protobuf:"bytes,1,opt,name=contenido,proto3" json:"contenido,omitempty"`
	Remitente     string                 `protobuf:"bytes,2,opt,name=remitente,proto3" json:"remitente,omitempty"`
	Canal         string                 `protobuf:"bytes,3,opt,name=canal,proto3" json:"canal,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeTexto) Reset() {
	*x = MensajeTexto{}
	mi := &file_mom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeTexto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeTexto) ProtoMessage() {}

func (x *MensajeTexto) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeTexto.ProtoReflect.Descriptor instead.
func (*MensajeTexto) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{6}
}

func (x *MensajeTexto) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

func (x *MensajeTexto) GetRemitente() string {
	if x != nil {
		return x.Remitente
	}
	return ""
}

func (x *MensajeTexto) GetCanal() string {
	if x != nil {
		return x.Canal
	}
	return ""
}

func (x *MensajeTexto) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ListaMensajes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensajes      []*MensajeTexto        `protobuf:"bytes,1,rep,name=mensajes,proto3" json:"mensajes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaMensajes) Reset() {
	*x = ListaMensajes{}
	mi := &file_mom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaMensajes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaMensajes) ProtoMessage() {}

func (x *ListaMensajes) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaMensajes.ProtoReflect.Descriptor instead.
func (*ListaMensajes) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{7}
}

func (x *ListaMensajes) GetMensajes() []*MensajeTexto {
	if x != nil {
		return x.Mensajes
	}
	return nil
}

type ListaNombres struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombres       []string               `protobuf:"bytes,1,rep,name=nombres,proto3" json:"nombres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaNombres) Reset() {
	*x = ListaNombres{}
	mi := &file_mom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaNombres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaNombres) ProtoMessage() {}

func (x *ListaNombres) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaNombres.ProtoReflect.Descriptor instead.
func (*ListaNombres) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{8}
}

func (x *ListaNombres) GetNombres() []string {
	if x != nil {
		return x.Nombres
	}
	return nil
}

type EventoReplica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Entidad       string                 `protobuf:"bytes,3,opt,name=entidad,proto3" json:"entidad,omitempty"`
	Datos         string                 `protobuf:"bytes,4,opt,name=datos,proto3" json:"datos,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IdOrigen      string                 `protobuf:"bytes,6,opt,name=id_origen,json=idOrigen,proto3" json:"id_origen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventoReplica) Reset() {
	*x = EventoReplica{}
	mi := &file_mom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventoReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventoReplica) ProtoMessage() {}

func (x *EventoReplica) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventoReplica.ProtoReflect.Descriptor instead.
func (*EventoReplica) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{9}
}

func (x *EventoReplica) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventoReplica) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *EventoReplica) GetEntidad() string {
	if x != nil {
		return x.Entidad
	}
	return ""
}

func (x *EventoReplica) GetDatos() string {
	if x != nil {
		return x.Datos
	}
	return ""
}

func (x *EventoReplica) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EventoReplica) GetIdOrigen() string {
	if x != nil {
		return x.IdOrigen
	}
	return ""
}

type ListaEventos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eventos       []*EventoReplica       `protobuf:"bytes,1,rep,name=eventos,proto3" json:"eventos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaEventos) Reset() {
	*x = ListaEventos{}
	mi := &file_mom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaEventos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaEventos) ProtoMessage() {}

func (x *ListaEventos) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaEventos.ProtoReflect.Descriptor instead.
func (*ListaEventos) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{10}
}

func (x *ListaEventos) GetEventos() []*EventoReplica {
	if x != nil {
		return x.Eventos
	}
	return nil
}

type EventosRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DesdeTimestamp string                 `protobuf:"bytes,1,opt,name=desde_timestamp,json=desdeTimestamp,proto3" json:"desde_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventosRequest) Reset() {
	*x = EventosRequest{}
	mi := &file_mom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventosRequest) ProtoMessage() {}

func (x *EventosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventosRequest.ProtoReflect.Descriptor instead.
func (*EventosRequest) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{11}
}

func (x *EventosRequest) GetDesdeTimestamp() string {
	if x != nil {
		return x.DesdeTimestamp
	}
	return ""
}

type PendientesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodoDestino   string                 `protobuf:"bytes,1,opt,name=nodo_destino,json=nodoDestino,proto3" json:"nodo_destino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendientesRequest) Reset() {
	*x = PendientesRequest{}
	mi := &file_mom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendientesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendientesRequest) ProtoMessage() {}

func (x *PendientesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendientesRequest.ProtoReflect.Descriptor instead.
func (*PendientesRequest) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{12}
}

func (x *PendientesRequest) GetNodoDestino() string {
	if x != nil {
		return x.NodoDestino
	}
	return ""
}

type RespuestaSimple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaSimple) Reset() {
	*x = RespuestaSimple{}
	mi := &file_mom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaSimple) ProtoMessage() {}

func (x *RespuestaSimple) ProtoReflect() protoreflect.Message {
	mi := &file_mom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaSimple.ProtoReflect.Descriptor instead.
func (*RespuestaSimple) Descriptor() ([]byte, []int) {
	return file_mom_proto_rawDescGZIP(), []int{13}
}

func (x *RespuestaSimple) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaSimple) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_mom_proto protoreflect.FileDescriptor

const file_mom_proto_rawDesc = "" +
	"\n" +
	"\tmom.proto\x12\x03mom\"F\n" +
	"\fCredenciales\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\x12TokenConExpiracion\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"expiracion\x18\x03 \x01(\tR\n" +
	"expiracion\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\">\n" +
	"\x0eAccionConToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"]\n" +
	"\x0fMensajeConToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tcontenido\x18\x03 \x01(\tR\tcontenido\"q\n" +
	"\x17AutorizacionColaRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12(\n" +
	"\x0fusuarioObjetivo\x18\x03 \x01(\tR\x0fusuarioObjetivo\"~\n" +
	"\fMensajeTexto\x12\x1c\n" +
	"\tcontenido\x18\x01 \x01(\tR\tcontenido\x12\x1c\n" +
	"\tremitente\x18\x02 \x01(\tR\tremitente\x12\x14\n" +
	"\x05canal\x18\x03 \x01(\tR\x05canal\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\">\n" +
	"\rListaMensajes\x12-\n" +
	"\bmensajes\x18\x01 \x03(\v2\x11.mom.MensajeTextoR\bmensajes\"(\n" +
	"\fListaNombres\x12\x18\n" +
	"\anombres\x18\x01 \x03(\tR\anombres\"\x9e\x01\n" +
	"\rEventoReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x18\n" +
	"\aentidad\x18\x03 \x01(\tR\aentidad\x12\x14\n" +
	"\x05datos\x18\x04 \x01(\tR\x05datos\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tid_origen\x18\x06 \x01(\tR\bidOrigen\"<\n" +
	"\fListaEventos\x12,\n" +
	"\aeventos\x18\x01 \x03(\v2\x12.mom.EventoReplicaR\aeventos\"9\n" +
	"\x0eEventosRequest\x12'\n" +
	"\x0fdesde_timestamp\x18\x01 \x01(\tR\x0edesdeTimestamp\"6\n" +
	"\x11PendientesRequest\x12!\n" +
	"\fnodo_destino\x18\x01 \x01(\tR\vnodoDestino\"A\n" +
	"\x0fRespuestaSimple\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xd6\b\n" +
	"\n" +
	"MomService\x12;\n" +
	"\x10RegistrarUsuario\x12\x11.mom.Credenciales\x1a\x14.mom.RespuestaSimple\x122\n" +
	"\x11AutenticarUsuario\x12\x11.mom.Credenciales\x1a\n" +
	".mom.Token\x12D\n" +
	"\x13GuardarTokenReplica\x12\x17.mom.TokenConExpiracion\x1a\x14.mom.RespuestaSimple\x126\n" +
	"\tCrearCola\x12\x13.mom.AccionConToken\x1a\x14.mom.RespuestaSimple\x129\n" +
	"\fEliminarCola\x12\x13.mom.AccionConToken\x1a\x14.mom.RespuestaSimple\x12J\n" +
	"\x14AutorizarUsuarioCola\x12\x1c.mom.AutorizacionColaRequest\x1a\x14.mom.RespuestaSimple\x12?\n" +
	"\x11EnviarMensajeCola\x12\x14.mom.MensajeConToken\x1a\x14.mom.RespuestaSimple\x12=\n" +
	"\x13ConsumirMensajeCola\x12\x13.mom.AccionConToken\x1a\x11.mom.MensajeTexto\x12,\n" +
	"\vListarColas\x12\n" +
	".mom.Token\x1a\x11.mom.ListaNombres\x128\n" +
	"\vCrearTopico\x12\x13.mom.AccionConToken\x1a\x14.mom.RespuestaSimple\x12;\n" +
	"\x0eEliminarTopico\x12\x13.mom.AccionConToken\x1a\x14.mom.RespuestaSimple\x12>\n" +
	"\x11SuscribirseTopico\x12\x13.mom.AccionConToken\x1a\x14.mom.RespuestaSimple\x12>\n" +
	"\x10PublicarEnTopico\x12\x14.mom.MensajeConToken\x1a\x14.mom.RespuestaSimple\x12>\n" +
	"\x13ConsumirDesdeTopico\x12\x13.mom.AccionConToken\x1a\x12.mom.ListaMensajes\x12.\n" +
	"\rListarTopicos\x12\n" +
	".mom.Token\x1a\x11.mom.ListaNombres\x12?\n" +
	"\x13EnviarEventoReplica\x12\x12.mom.EventoReplica\x1a\x14.mom.RespuestaSimple\x12:\n" +
	"\x10SolicitarEventos\x12\x13.mom.EventosRequest\x1a\x11.mom.ListaEventos\x12@\n" +
	"\x13SolicitarPendientes\x12\x16.mom.PendientesRequest\x1a\x11.mom.ListaEventosB\x05Z\x03/pbb\x06proto3"

var (
	file_mom_proto_rawDescOnce sync.Once
	file_mom_proto_rawDescData []byte
)

func file_mom_proto_rawDescGZIP() []byte {
	file_mom_proto_rawDescOnce.Do(func() {
		file_mom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mom_proto_rawDesc), len(file_mom_proto_rawDesc)))
	})
	return file_mom_proto_rawDescData
}

var file_mom_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mom_proto_goTypes = []any{
	(*Credenciales)(nil),            // 0: mom.Credenciales
	(*TokenConExpiracion)(nil),      // 1: mom.TokenConExpiracion
	(*Token)(nil),                   // 2: mom.Token
	(*AccionConToken)(nil),          // 3: mom.AccionConToken
	(*MensajeConToken)(nil),         // 4: mom.MensajeConToken
	(*AutorizacionColaRequest)(nil), // 5: mom.AutorizacionColaRequest
	(*MensajeTexto)(nil),            // 6: mom.MensajeTexto
	(*ListaMensajes)(nil),           // 7: mom.ListaMensajes
	(*ListaNombres)(nil),            // 8: mom.ListaNombres
	(*EventoReplica)(nil),           // 9: mom.EventoReplica
	(*ListaEventos)(nil),            // 10: mom.ListaEventos
	(*EventosRequest)(nil),          // 11: mom.EventosRequest
	(*PendientesRequest)(nil),       // 12: mom.PendientesRequest
	(*RespuestaSimple)(nil),         // 13: mom.RespuestaSimple
}
var file_mom_proto_depIdxs = []int32{
	6,  // 0: mom.ListaMensajes.mensajes:type_name -> mom.MensajeTexto
	9,  // 1: mom.ListaEventos.eventos:type_name -> mom.EventoReplica
	0,  // 2: mom.MomService.RegistrarUsuario:input_type -> mom.Credenciales
	0,  // 3: mom.MomService.AutenticarUsuario:input_type -> mom.Credenciales
	1,  // 4: mom.MomService.GuardarTokenReplica:input_type -> mom.TokenConExpiracion
	3,  // 5: mom.MomService.CrearCola:input_type -> mom.AccionConToken
	3,  // 6: mom.MomService.EliminarCola:input_type -> mom.AccionConToken
	5,  // 7: mom.MomService.AutorizarUsuarioCola:input_type -> mom.AutorizacionColaRequest
	4,  // 8: mom.MomService.EnviarMensajeCola:input_type -> mom.MensajeConToken
	3,  // 9: mom.MomService.ConsumirMensajeCola:input_type -> mom.AccionConToken
	2,  // 10: mom.MomService.ListarColas:input_type -> mom.Token
	3,  // 11: mom.MomService.CrearTopico:input_type -> mom.AccionConToken
	3,  // 12: mom.MomService.EliminarTopico:input_type -> mom.AccionConToken
	3,  // 13: mom.MomService.SuscribirseTopico:input_type -> mom.AccionConToken
	4,  // 14: mom.MomService.PublicarEnTopico:input_type -> mom.MensajeConToken
	3,  // 15: mom.MomService.ConsumirDesdeTopico:input_type -> mom.AccionConToken
	2,  // 16: mom.MomService.ListarTopicos:input_type -> mom.Token
	9,  // 17: mom.MomService.EnviarEventoReplica:input_type -> mom.EventoReplica
	11, // 18: mom.MomService.SolicitarEventos:input_type -> mom.EventosRequest
	12, // 19: mom.MomService.SolicitarPendientes:input_type -> mom.PendientesRequest
	13, // 20: mom.MomService.RegistrarUsuario:output_type -> mom.RespuestaSimple
	2,  // 21: mom.MomService.AutenticarUsuario:output_type -> mom.Token
	13, // 22: mom.MomService.GuardarTokenReplica:output_type -> mom.RespuestaSimple
	13, // 23: mom.MomService.CrearCola:output_type -> mom.RespuestaSimple
	13, // 24: mom.MomService.EliminarCola:output_type -> mom.RespuestaSimple
	13, // 25: mom.MomService.AutorizarUsuarioCola:output_type -> mom.RespuestaSimple
	13, // 26: mom.MomService.EnviarMensajeCola:output_type -> mom.RespuestaSimple
	6,  // 27: mom.MomService.ConsumirMensajeCola:output_type -> mom.MensajeTexto
	8,  // 28: mom.MomService.ListarColas:output_type -> mom.ListaNombres
	13, // 29: mom.MomService.CrearTopico:output_type -> mom.RespuestaSimple
	13, // 30: mom.MomService.EliminarTopico:output_type -> mom.RespuestaSimple
	13, // 31: mom.MomService.SuscribirseTopico:output_type -> mom.RespuestaSimple
	13, // 32: mom.MomService.PublicarEnTopico:output_type -> mom.RespuestaSimple
	7,  // 33: mom.MomService.ConsumirDesdeTopico:output_type -> mom.ListaMensajes
	8,  // 34: mom.MomService.ListarTopicos:output_type -> mom.ListaNombres
	13, // 35: mom.MomService.EnviarEventoReplica:output_type -> mom.RespuestaSimple
	10, // 36: mom.MomService.SolicitarEventos:output_type -> mom.ListaEventos
	10, // 37: mom.MomService.SolicitarPendientes:output_type -> mom.ListaEventos
	20, // [20:38] is the sub-list for method output_type
	2,  // [2:20] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_mom_proto_init() }
func file_mom_proto_init() {
	if File_mom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mom_proto_rawDesc), len(file_mom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mom_proto_goTypes,
		DependencyIndexes: file_mom_proto_depIdxs,
		MessageInfos:      file_mom_proto_msgTypes,
	}.Build()
	File_mom_proto = out.File
	file_mom_proto_goTypes = nil
	file_mom_proto_depIdxs = nil
}
